//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSL.Cars.Parse.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[@class=\"solidNavBar\"]/a")]
        public string LAST_PAGE_NODE {
            get {
                return ((string)(this["LAST_PAGE_NODE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[@class=\"srp-listing-body-right\"]")]
        public string LISTING_SEARCH_RESULTS {
            get {
                return ((string)(this["LISTING_SEARCH_RESULTS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div[@class=\"srp-listing-price\"]")]
        public string LISTING_RESULT_PRICE {
            get {
                return ((string)(this["LISTING_RESULT_PRICE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div[@class=\"srp-listing-title\"]/a")]
        public string LISTING_RESULT_LINK {
            get {
                return ((string)(this["LISTING_RESULT_LINK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div[@class=\"srp-listing-title\"]/a")]
        public string LISTING_RESULT_ID {
            get {
                return ((string)(this["LISTING_RESULT_ID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"specificationsTable\"]/tr/td[text()=\'VIN:\']")]
        public string LISTING_VIN {
            get {
                return ((string)(this["LISTING_VIN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"specificationsTable\"]/tr/td[text()=\'Mileage:\']")]
        public string LISTING_MILEAGE {
            get {
                return ((string)(this["LISTING_MILEAGE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"specificationsTable\"]/tr/td[text()=\'Exterior Color:\']")]
        public string LISTING_EXT_COLOR {
            get {
                return ((string)(this["LISTING_EXT_COLOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"specificationsTable\"]/tr/td[text()=\'Interior Color:\']")]
        public string LISTING_INT_COLOR {
            get {
                return ((string)(this["LISTING_INT_COLOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"specificationsTable\"]/tr/td[text()=\'Year:\']")]
        public string LISTING_YEAR {
            get {
                return ((string)(this["LISTING_YEAR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"specificationsTable\"]/tr/td[text()=\'Make:\']")]
        public string LISTING_MAKE {
            get {
                return ((string)(this["LISTING_MAKE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"specificationsTable\"]/tr/td[text()=\'Model:\']")]
        public string LISTING_MODEL {
            get {
                return ((string)(this["LISTING_MODEL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"specificationsTable\"]/tr/td[text()=\'Trim:\']")]
        public string LISTING_TRIM {
            get {
                return ((string)(this["LISTING_TRIM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"specificationsTable\"]/tr/td[text()=\'Body:\']")]
        public string LISTING_BODY {
            get {
                return ((string)(this["LISTING_BODY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"specificationsTable\"]/tr/td[text()=\'Title:\']")]
        public string LISTING_TITLE {
            get {
                return ((string)(this["LISTING_TITLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"specificationsTable\"]/tr/td[text()=\'Transmission:\']")]
        public string LISTING_TRANSMISSION {
            get {
                return ((string)(this["LISTING_TRANSMISSION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"specificationsTable\"]/tr/td[text()=\'Liters:\']")]
        public string LISTING_LITERS {
            get {
                return ((string)(this["LISTING_LITERS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table[@id=\"specificationsTable\"]/tr/td[text()=\'Cylinders:\']")]
        public string LISTING_CYLINDERS {
            get {
                return ((string)(this["LISTING_CYLINDERS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//h2[@class=\"location\"]")]
        public string LISTING_CITY {
            get {
                return ((string)(this["LISTING_CITY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[@id=\"description\"]")]
        public string LISTING_DESCRIPTION {
            get {
                return ((string)(this["LISTING_DESCRIPTION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//div[contains(@class,\'contactName\')]")]
        public string CONTACT_NAME {
            get {
                return ((string)(this["CONTACT_NAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//a[contains(@href,\'tel: \')]")]
        public string CONTACT_PHONE {
            get {
                return ((string)(this["CONTACT_PHONE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ksl.com/auto/listing/{LISTING_ID}")]
        public string LISTING_LINK {
            get {
                return ((string)(this["LISTING_LINK"]));
            }
        }
    }
}
